name: Release PuzzleSolver

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'

jobs:
  build-test-publish:
    name: Build & Test & Publish
    runs-on: ubuntu-latest
    
    env:
      VERSION: 1.0
      CONFIGURATION: Release
      TARGET_RIDS: "osx-arm64 linux-x64 win-x64"
    
    steps:
      - name: Extract version
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        
      - name: Cloning repository
        uses: actions/checkout@v6
        
      - name: Installing dotnet
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json
        
      - name: Testing solution
        run: dotnet test -c $CONFIGURATION
        
      - name: Publishing cli
        run: |
          mkdir -p artifacts/dist
          for RID in $TARGET_RIDS; do
            dotnet publish src/PuzzleSolver.Cli/PuzzleSolver.Cli.csproj \
              -p:Version=$VERSION \
              -c $CONFIGURATION \
              -r $RID \
              -o artifacts/publish/$RID \
              -p:PublishSingleFile=true \
              --self-contained
            
            if [[ "$RID" == win-* ]]; then
              mv "artifacts/publish/$RID/PuzzleSolver.Cli.exe" "artifacts/dist/puzzle-solver-$RID.exe"
            else
              mv "artifacts/publish/$RID/PuzzleSolver.Cli" "artifacts/dist/puzzle-solver-$RID"
            fi
          done
          
      - name: Uploading artifacts
        uses: actions/upload-artifact@v6
        with:
          path: artifacts/dist
          
  sign-macos:
    name: Sign macOS Binary
    runs-on: macos-latest
    needs: build-test-publish
    permissions:
      contents: write
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7

      - name: AdHoc Sign
        run: codesign --sign - --force puzzle-solver-osx-arm64

      - name: Upload artifacts to Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: ./*